### ISSUE TITLE
Connection Pooling for Dynamic Backends

### ISSUE THREAD

**Issue by mattg-sigsci** [fastly/compute-sdk-go#106]
## Problem

For dynamic backends, the Rust crate has an `enabled_pooling()` function for its `BackendBuilder` type. `compute-go-sdk` appears to have no equivalent function on `BackendOptions` and no way to enable connection pooling for a dynamic backend. This causes connection timeout errors when trying to connect anew on every request.

## Expectation

There should be some way to enable connection pooling for dynamic backends.

**Comment by joeshaw** [comment]
To be clear: connection pooling is on by default, this setting would allow you to _disable_ it.

**Comment by mattg-sigsci** [comment]
Oh. Rats.
