### ISSUE TITLE
I need to use TCP on Fastly Compute to connect to a cloud database! But it doesn't have access to it.

### ISSUE THREAD

**Issue by masx200** [fastly/compute-sdk-go#107]
I need to use TCP on Fastly Compute to connect to a cloud database!
But it doesn't have access to it.

**Comment by joeshaw** [comment]
Thanks.  You're correct that the Compute platform doesn't currently have direct TCP support yet. I've passed this along to our product team for future enhancement.

As we're trying to keep this issue tracker focused on issues with the Go SDK specifically, I'm going to close the issue.
