### ISSUE TITLE
How do I run a static file server on Fastly Compute Edge?

### ISSUE THREAD

**Issue by masx200** [fastly/compute-sdk-go#108]
How do I run a static file server on Fastly Compute Edge?

**Comment by cee-dub** [comment]
This question is probably more likely to be answered in the [Fastly Community Forum](https://community.fastly.com/).

While I'm here, I can think of several ways:
- using [embed.FS](https://pkg.go.dev/embed#hdr-Directives) and [fsthttp.Adapt](https://pkg.go.dev/github.com/fastly/compute-sdk-go/fsthttp#Adapt)
- using a [KV store](https://docs.fastly.com/en/guides/working-with-kv-stores) for static assets
- using the [readthrough cache](https://www.fastly.com/documentation/guides/concepts/edge-state/cache/#readthrough-cache) to any origin (this requires something outside of Compute, so it doesn't really count)
