### ISSUE TITLE
Feature Request: KVStore.delete

### ISSUE THREAD

**Issue by dios-david** [fastly/compute-sdk-go#109]
Currently `KVStore` only has `Lookup` and `Insert` methods exposed to Go: https://github.com/fastly/compute-sdk-go/blob/1a691315532d165c4b9791c164a769eb3c187324/kvstore/kvstore.go#L95-L131

Both the [Rust SDK](https://docs.rs/fastly/latest/src/fastly/kv_store.rs.html#143-148) and the [JS SDK](https://github.com/fastly/js-compute-runtime/pull/751) support deleting entries from a KVStore.

Is there a plan to add a `Delete` method to `KVStore` in the Go SDK as well? Or is there any undocumented way to delete entries (e.g. by calling `Insert` with an empty value etc)?

**Comment by athomason** [comment]
Hi @dios-david, thanks for pointing this out. The implementation is straightforward but I've noticed some inconsistencies between the SDKs and production/Viceroy environments w.r.t. error behavior that I'll raise with the team.

**Comment by dios-david** [comment]
Thanks a lot @athomason ! 🎉
