### ISSUE TITLE
Implement hostcall for obtaining server IP

### ISSUE THREAD

**Issue by kphillips** [fastly/compute-sdk-go#126]
A hostcall to expose the IP address on which the server received the HTTP request was recently added. Support has already been added in the Rust SDK (see https://docs.rs/fastly/latest/fastly/handle/fn.server_ip_addr.html), and needs to be added to the Go SDK.

**Comment by dgryski** [comment]
With https://github.com/fastly/compute-sdk-go/pull/127 merged can we close this?

**Comment by dgryski** [comment]
Done.
