### ISSUE TITLE
configstore: no error when opening a config store that does not exist

### ISSUE THREAD

**Issue by awilliams-fastly** [fastly/compute-sdk-go#128]
In the following sample code, no error is returned from `configstore.Open("DOES_NOT_EXIST")`, but a `configstore.ErrStoreNotFound` error _is_ returned from `cs.Get("cat")`. 

```go
cs, err := configstore.Open("DOES_NOT_EXIST") // err == nil
switch {
case errors.Is(err, configstore.ErrStoreNotFound):
        fsthttp.Error(w, "config store not found: configstore.Open", fsthttp.StatusNotFound)
        return
case err != nil:
        fsthttp.Error(w, fmt.Sprintf("error opening config store: %s", err.Error()), fsthttp.StatusInternalServerError)
        return
}

v, err := cs.Get("cat") // err == configstore.ErrStoreNotFound
switch {
case errors.Is(err, configstore.ErrStoreNotFound):
        fsthttp.Error(w, "config store not found: cs.Get", fsthttp.StatusNotFound)
        return
case errors.Is(err, configstore.ErrKeyNotFound):
        fsthttp.Error(w, "config store key not found", fsthttp.StatusNotFound)
        return
case err != nil:
        fsthttp.Error(w, fmt.Sprintf("error opening config store key: %s", err.Error()), fsthttp.StatusInternalServerError)
        return
}

```

To better match the Rust SDK, and to provide a better user experience, consider returning a `configstore.ErrStoreNotFound` from `configstore.Open` when the named config store does not exist.

Possibly related: #118

**Comment by dgryski** [comment]
The current `configstore` package uses the old hostcalls, which do not return an error for missing stores.

https://github.com/fastly/compute-sdk-go/blob/main/internal/abi/fastly/dictionary_guest.go#L62

So indeed the correct path forward is to switch to the new hostcalls.
