### ISSUE TITLE
Match objectstore.Lookup with rust and js sdks

### ISSUE THREAD

**Issue by JakeChampion** [fastly/compute-sdk-go#21]
In Rust, [Lookup](https://docs.rs/fastly/latest/fastly/struct.ObjectStore.html#method.lookup) returns a Result<Option<Body>, ObjectStoreError> and in [JavaScript](https://js-compute-reference-docs.edgecompute.app/docs/fastly:object-store/ObjectStore/prototype/get) it returns a ObjectStoreEntry | null 

These both allow the user to detect if the requested key has no value associated with it. I couldn’t find an equivalent in the Go SDK.

Can we update the Lookup implementation to make it possible to detect whether there is no value for the a key without having to consume any of bytes from the returned io.Reader instance?

This could be done by checking if the body_handle has not changed after calling the `fastly_object_store.lookup` wit function. When a key is not found, the ABI will not update the provided body_handle.

**Comment by dgryski** [comment]
https://github.com/fastly/compute-sdk-go/pull/22
