### ISSUE TITLE
Improve returned errors from hostcalls

### ISSUE THREAD

**Issue by dgryski** [fastly/compute-sdk-go#23]
As part of #22 we map an internal Fastly error code into a more user-friendly Go error.  Doing this for the entire API surface could arguably make the SDK nicer but also add a significant maintenance burden.

Another alternative would be to make the internal Fastly error package out of `internal` and make them less opaque.

**Comment by dgryski** [comment]
Note that we already map the internal errors for `edgedict` (at least) https://github.com/fastly/compute-sdk-go/blob/main/edgedict/dictionary.go#L41

**Comment by joeshaw** [comment]
I also do this (to a much less comprehensive degree) in the secret store PR: https://github.com/fastly/compute-sdk-go/pull/19/files#diff-c2eb46139ff479d3b0bfbcaa4e94f75d850ca099c05b86f72007f43daad932a6R34-R38

**Comment by joeshaw** [comment]
Fixed by #85.
