### ISSUE TITLE
kvstore `Entry` exposes embedded `io.Reader` but consumes its contents in `String`

### ISSUE THREAD

**Issue by joeshaw** [fastly/compute-sdk-go#40]
[Code review comment](https://github.com/fastly/compute-sdk-go/pull/34/files#r1167628240) from @peterbourgon:

> Embedding an io.Reader in this way allows callers to treat Entry as an io.Reader directly, which doesn't seem to be correct, as methods like String consume from that Reader and mutate internal state in a way that callers aren't able to do.

I suspect he's right but I don't know the intention here.  @dgryski, do you know?

Un-embedding `io.Reader` would mean a breaking API change, so it'd at least need a bump to the next 0.x "major" version.  (0.2.0 as of this writing)

**Comment by dgryski** [comment]
The idea was so that you could stream a response from the KV store out to the client without having to hold the entire value in memory.

**Comment by peterbourgon** [comment]
A single type that implements both io.Reader and fmt.Stringer is very tricky. A correct implementation must allow a caller to call Read with a buffer of size 3 and get the first 3 bytes of the value, and then call String and get the entire value, and then call Read again with a huge buffer and get all of the bytes from the 4th byte forward. I'm not sure how you'd do this without caching the value in memory.

My suggestion would be to provide two separate types, constructors, etc. for values: one which implements io.Reader, and one which implements fmt.Stringer (or is just a string directly).

**Comment by joeshaw** [comment]
Another option could be to replace `String()` with a method that makes it more clear that it consumes the reader.  Essentially `io.ReadAll` but to a string rather than byte slice.

**Comment by joeshaw** [comment]
It was too late for us to change this behavior, so I've documented it instead.  In practice I think few people will run into it, since they'll be using KV store values in one of two rather different ways (small data where strings are nice, or larger files they probably want to stream to clients or other backends)
