### ISSUE TITLE
All I get is "poll: Fastly error: Error"

### ISSUE THREAD

**Issue by advdv** [fastly/compute-sdk-go#87]
I'm trying the basic example proxy example on my own test backend:  `https://autov.stag.v3.crewlinker.com/check/health` but all I get is `poll: Fastly error: error` without any way to debug. It works fine when running it with  `fastly compute serve`

This is basically developing blind and I have to give up on doing anything with compute@edge for now. Hopefully this can be improved

**Comment by joeshaw** [comment]
This should be fixed by https://github.com/fastly/compute-sdk-go/pull/81.  If you want to try it out, check that PR out locally and add something like this to your `go.mod`:

```
replace github.com/fastly/compute-sdk-go => /path/to/checked-out/compute-sdk-go
```

**Comment by joeshaw** [comment]
To be clear, by "should be fixed" I mean "will report a more meaningful error."

If you want to post your code we can take a look and see if we can identify the issue.  My first guess is that your backend isn't defined on the Fastly service, or that the name doesn't match what's in your code.  Hope this helps!

**Comment by advanderveer** [comment]
I had to switch to just using vcl and that got my setup working, for now I have to move on. Maybe later I have more time to try out the pr. But it sounds like 81 is definite win and sounds like it should fix this issue.
